[project]
name = "gemini-efficient-api-calls"
version = "0.1.1"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["gemini_efficient_api_calls*"]