[project]
name = "gemini_batcher"
version = "0.6.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["gemini_batcher*"]